export const primary = "#8FDFDE";
export const primaryLight = "#E1ECEB";
export const secondary = "#D1345B";
export const lightGrey = "#EFEFEF";
export const grey = "#C9C9C9";
export const darkGrey = "#3A3A3A";
// export const darkGrey = '#070707';
export const black = "#070707";
export const white = "#FEFEFE";
